<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::table('refund_queue', function (Blueprint $table) {
            $table->boolean('AutoGenerated')->default(false)->after('ProofOfTransfer');
            $table->enum('RefundMethod', ['manual', 'auto', 'api'])->default('manual')->after('AutoGenerated');
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::table('refund_queue', function (Blueprint $table) {
            $table->dropColumn(['AutoGenerated', 'RefundMethod']);
        });
    }
};
