<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class RefundQueue extends Model
{
    use HasFactory;

    protected $table = 'refund_queue';
    protected $primaryKey = 'RefundQueueID';

    protected $fillable = [
        'DepositID',
        'BookingID',
        'UserID',
        'RefundAmount',
        'Status',
        'BankName',
        'BankAccountNumber',
        'BankAccountHolderName',
        'RefundReference',
        'Notes',
        'ProcessedAt',
        'ProcessedBy',
        'ProofOfTransfer',
        'AutoGenerated',
        'RefundMethod',
    ];

    protected $casts = [
        'ProcessedAt' => 'datetime',
        'RefundAmount' => 'decimal:2',
        'AutoGenerated' => 'boolean',
    ];

    /**
     * Get the deposit associated with this refund queue item
     */
    public function deposit()
    {
        return $this->belongsTo(Deposit::class, 'DepositID', 'DepositID');
    }

    /**
     * Get the booking associated with this refund queue item
     */
    public function booking()
    {
        return $this->belongsTo(Booking::class, 'BookingID', 'BookingID');
    }

    /**
     * Get the user (renter) who will receive the refund
     */
    public function user()
    {
        return $this->belongsTo(User::class, 'UserID', 'UserID');
    }

    /**
     * Get the admin who processed the refund
     */
    public function processor()
    {
        return $this->belongsTo(User::class, 'ProcessedBy', 'UserID');
    }

    /**
     * Generate automatic refund reference
     * Format: RMT-YYYYMMDD-#####
     */
    public static function generateRefundReference($refundQueueID)
    {
        $date = now()->format('Ymd');
        return sprintf('RMT-%s-%05d', $date, $refundQueueID);
    }

    /**
     * Auto-complete the refund with generated reference
     */
    public function autoComplete($adminId)
    {
        \DB::beginTransaction();
        try {
            // Generate reference
            $this->RefundReference = self::generateRefundReference($this->RefundQueueID);
            $this->RefundMethod = 'auto';
            $this->AutoGenerated = true;
            $this->Status = 'completed';
            $this->ProcessedAt = now();
            $this->ProcessedBy = $adminId;
            $this->save();

            // Update deposit
            $deposit = $this->deposit;
            $deposit->Status = 'refunded';
            $deposit->RefundDate = now();
            $deposit->RefundReference = $this->RefundReference;
            $deposit->save();

            \DB::commit();
            return true;
        } catch (\Exception $e) {
            \DB::rollback();
            throw $e;
        }
    }
}
